CREATE TABLE CORE.POWER (
	ID SERIAL PRIMARY KEY,
	COMPONENT_ID INTEGER NOT NULL REFERENCES CORE.COMPONENTS (ID),
	EFFICIENCY NUMERIC(5, 4),
	POWER_OUTPUT INTEGER,
	TEMPERATURE_TOLERANCE_MIN INTEGER,
	TEMPERATURE_TOLERANCE_MAX INTEGER,
	DEGRADATION_RATE NUMERIC(5, 4),
	ADVANTAGES VARCHAR,
	DISADVANTAGES VARCHAR
)

